name: fastapi
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fastapi-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  fastapi-network:
    driver: bridge
